use std::path::PathBuf;

use anyhow::{Result, anyhow};
use dialoguer::{Confirm, Input, Select, theme::ColorfulTheme};

use crate::{
    catalog::load_templates,
    cli::{InitArgs, TemplateChoice},
    config::{
        AiToolsConfig, AgentKind, BootstrapConfig, BranchStrategy, GenericTemplateConfig,
        GithubConfig, ProjectConfig, ReleaseChannel, ReleaseConfig, StarterConfig, TemplateKind,
        WorkflowConfig,
    },
};

pub fn resolve_config(args: &InitArgs) -> Result<StarterConfig> {
    if let Some(path) = &args.config {
        return StarterConfig::load(path);
    }
    if args.non_interactive {
        return build_non_interactive(args);
    }
    run_wizard(args)
}

fn run_wizard(args: &InitArgs) -> Result<StarterConfig> {
    let theme = ColorfulTheme::default();
    let templates = load_templates()?;
    let default_template = args
        .template
        .as_ref()
        .map(template_choice_to_kind)
        .unwrap_or(TemplateKind::PythonService);

    let choices: Vec<String> = templates
        .iter()
        .map(|spec| {
            format!(
                "{} - {}",
                spec.manifest.display_name, spec.manifest.description
            )
        })
        .collect();
    let selected = templates
        .iter()
        .position(|spec| spec.manifest.kind == default_template)
        .unwrap_or(0);
    let template_index = if args.template.is_some() {
        selected
    } else {
        Select::with_theme(&theme)
            .with_prompt("Project template")
            .default(selected)
            .items(&choices)
            .interact()?
    };
    let template = templates[template_index].manifest.kind;

    // Validate and get project name
    let name = loop {
        let input = match &args.name {
            Some(name) => name.clone(),
            None => Input::<String>::with_theme(&theme)
                .with_prompt("Project name")
                .interact_text()?,
        };

        // Validate name
        if input.trim().is_empty() {
            eprintln!("Error: Project name cannot be empty");
            if args.name.is_some() {
                return Err(anyhow!("Invalid project name: empty"));
            }
            continue;
        }
        if input.contains(' ') {
            eprintln!("Error: Project name cannot contain spaces");
            if args.name.is_some() {
                return Err(anyhow!("Invalid project name: contains spaces"));
            }
            continue;
        }
        break input;
    };

    let slug_default = slugify(&name);
    let slug = Input::<String>::with_theme(&theme)
        .with_prompt("Repository slug")
        .default(slug_default.clone())
        .interact_text()?;
    let target_path = match &args.path {
        Some(path) => path.clone(),
        None => Input::<String>::with_theme(&theme)
            .with_prompt("Target path")
            .default(slug.clone())
            .interact_text()?
            .into(),
    };
    let description = Input::<String>::with_theme(&theme)
        .with_prompt("Description")
        .default(format!("{name} generated by revi"))
        .interact_text()?;
    let github_enabled = Confirm::with_theme(&theme)
        .with_prompt("Generate GitHub workflows and templates?")
        .default(true)
        .interact()?;
    let codeowners = if github_enabled {
        Confirm::with_theme(&theme)
            .with_prompt("Include CODEOWNERS placeholder?")
            .default(false)
            .interact()?
    } else {
        false
    };
    let create_repo = if github_enabled {
        Confirm::with_theme(&theme)
            .with_prompt("Attempt GitHub repo creation with gh after scaffold?")
            .default(false)
            .interact()?
    } else {
        false
    };
    let owner = if create_repo {
        let input = Input::<String>::with_theme(&theme)
            .with_prompt("GitHub owner")
            .allow_empty(true)
            .interact_text()?;
        if input.trim().is_empty() {
            None
        } else {
            Some(input)
        }
    } else {
        None
    };
    let ai_tools_enabled = Confirm::with_theme(&theme)
        .with_prompt("Generate AI coding CLI compatibility files?")
        .default(true)
        .interact()?;
    let use_ai_api = if ai_tools_enabled {
        Confirm::with_theme(&theme)
            .with_prompt("Use AI API to generate skill/agent content?")
            .default(false)
            .interact()?
    } else {
        false
    };
    let ai_provider = if use_ai_api {
        let choices = vec!["MiniMax", "OpenAI (future)", "Claude (future)"];
        let selected = Select::with_theme(&theme)
            .with_prompt("Select AI provider")
            .default(0)
            .items(&choices)
            .interact()?;
        choices[selected].to_lowercase().split_whitespace().next().unwrap_or("minimax").to_string()
    } else {
        "minimax".to_string()
    };
    let ai_tools = if ai_tools_enabled {
        let agent_options = vec!["Codex", "Claude Code", "Gemini CLI"];
        let agent_defaults = vec![true, true, true];
        let selected_agent_indices = dialoguer::MultiSelect::with_theme(&theme)
            .with_prompt("Select AI agents to adapt (space to select, enter to confirm)")
            .items(&agent_options)
            .defaults(&agent_defaults)
            .interact()?
            .into_iter()
            .collect::<Vec<_>>();

        let selected_agents: Vec<AgentKind> = selected_agent_indices
            .iter()
            .filter(|&&i| i < 3)
            .map(|&i| match i {
                0 => AgentKind::Codex,
                1 => AgentKind::ClaudeCode,
                2 => AgentKind::GeminiCli,
                _ => AgentKind::Codex,
            })
            .collect();

        AiToolsConfig {
            enabled: true,
            selected_agents,
            tool_docs: Confirm::with_theme(&theme)
                .with_prompt("Generate docs/AI_TOOLS.md and shared AI tool guidance?")
                .default(true)
                .interact()?,
            command_helpers: Confirm::with_theme(&theme)
                .with_prompt("Include command helper sections in AI tool files?")
                .default(true)
                .interact()?,
            skills: Confirm::with_theme(&theme)
                .with_prompt("Generate Claude Code skill files (.claude/skills/)?")
                .default(true)
                .interact()?,
            agents: Confirm::with_theme(&theme)
                .with_prompt("Generate agent configuration files?")
                .default(false)
                .interact()?,
            use_ai_api,
            ai_provider,
        }
    } else {
        AiToolsConfig {
            enabled: false,
            ..AiToolsConfig::default()
        }
    };
    let generic = if template == TemplateKind::GenericProject {
        GenericTemplateConfig {
            agent_context_files: Confirm::with_theme(&theme)
                .with_prompt("Generate AI agent context files in docs/?")
                .default(true)
                .interact()?,
            scripts_dir: Confirm::with_theme(&theme)
                .with_prompt("Create scripts/ placeholder directory?")
                .default(true)
                .interact()?,
            placeholder_workflows: Confirm::with_theme(&theme)
                .with_prompt("Generate placeholder CI and release workflows?")
                .default(true)
                .interact()?,
            docs_expanded: Confirm::with_theme(&theme)
                .with_prompt("Create expanded docs placeholders?")
                .default(true)
                .interact()?,
        }
    } else {
        GenericTemplateConfig::default()
    };

    let config = StarterConfig {
        schema_version: 1,
        project: ProjectConfig {
            name: name.clone(),
            slug: slug.clone(),
            template,
            path: PathBuf::from(target_path),
            description,
            version: "0.1.0".to_string(),
        },
        workflow: WorkflowConfig {
            branch_strategy: BranchStrategy::LightweightRelease,
            release: ReleaseConfig {
                channel: ReleaseChannel::GithubReleaseAndRegistry,
                registry: matches!(template, TemplateKind::PythonService),
                github_release: true,
            },
        },
        bootstrap: BootstrapConfig {
            init_git: true,
            initial_commit: true,
        },
        ai_tools,
        github: GithubConfig {
            enabled: github_enabled,
            create_repo,
            owner,
            repo: Some(slug),
            push_after_create: create_repo,
            codeowners,
        },
        generic,
    };

    // Show confirmation summary
    let summary = format_config_summary(&config);
    println!("\n--- Configuration Summary ---");
    println!("{}", summary);
    println!("----------------------------");

    let confirmed = Confirm::with_theme(&theme)
        .with_prompt("Proceed with scaffolding?")
        .default(true)
        .interact()?;

    if !confirmed {
        return Err(anyhow!("Scaffolding cancelled by user"));
    }

    Ok(config)
}

fn format_config_summary(config: &StarterConfig) -> String {
    let mut lines = Vec::new();
    lines.push(format!("Project: {} ({})", config.project.name, config.project.slug));
    lines.push(format!("Template: {}", config.project.template.template_id()));
    lines.push(format!("Path: {}", config.project.path.display()));
    lines.push(format!("Description: {}", config.project.description));

    if config.github.enabled {
        lines.push("GitHub: enabled".to_string());
        if config.github.create_repo {
            lines.push(format!("  - Create repo for: {}", config.github.owner.clone().unwrap_or_default()));
        }
        if config.github.codeowners {
            lines.push("  - CODEOWNERS: yes".to_string());
        }
    } else {
        lines.push("GitHub: disabled".to_string());
    }

    if config.ai_tools.enabled {
        let agent_names: Vec<&str> = config.ai_tools.selected_agents
            .iter()
            .map(|a| a.display_name())
            .collect();
        lines.push(format!("AI Tools: enabled ({})", agent_names.join(", ")));
        if config.ai_tools.use_ai_api {
            lines.push(format!("  - AI Provider: {}", config.ai_tools.ai_provider));
        }
        if config.ai_tools.skills {
            lines.push("  - Skills: yes".to_string());
        }
        if config.ai_tools.agents {
            lines.push("  - Agents: yes".to_string());
        }
    } else {
        lines.push("AI Tools: disabled".to_string());
    }

    if config.project.template == TemplateKind::GenericProject {
        lines.push("Generic options:".to_string());
        if config.generic.agent_context_files {
            lines.push("  - Agent context files: yes".to_string());
        }
        if config.generic.scripts_dir {
            lines.push("  - Scripts directory: yes".to_string());
        }
    }

    lines.join("\n")
}

fn build_non_interactive(args: &InitArgs) -> Result<StarterConfig> {
    let name = args
        .name
        .clone()
        .ok_or_else(|| anyhow!("--non-interactive requires --name"))?;
    let template = args
        .template
        .as_ref()
        .map(template_choice_to_kind)
        .ok_or_else(|| anyhow!("--non-interactive requires --template"))?;
    let slug = slugify(&name);
    let path = args.path.clone().unwrap_or_else(|| PathBuf::from(&slug));

    Ok(StarterConfig {
        schema_version: 1,
        project: ProjectConfig {
            name: name.clone(),
            slug: slug.clone(),
            template,
            path,
            description: format!("{name} generated by revi"),
            version: "0.1.0".to_string(),
        },
        workflow: WorkflowConfig {
            branch_strategy: BranchStrategy::LightweightRelease,
            release: ReleaseConfig {
                channel: ReleaseChannel::GithubReleaseAndRegistry,
                registry: matches!(template, TemplateKind::PythonService),
                github_release: true,
            },
        },
        bootstrap: BootstrapConfig {
            init_git: true,
            initial_commit: true,
        },
        ai_tools: AiToolsConfig::default(),
        github: GithubConfig {
            enabled: true,
            create_repo: false,
            owner: None,
            repo: Some(slug),
            push_after_create: false,
            codeowners: false,
        },
        generic: GenericTemplateConfig::default(),
    })
}

pub fn slugify(input: &str) -> String {
    let mut out = String::new();
    let mut prev_dash = false;
    for ch in input.chars() {
        let lower = ch.to_ascii_lowercase();
        if lower.is_ascii_alphanumeric() {
            out.push(lower);
            prev_dash = false;
        } else if !prev_dash {
            out.push('-');
            prev_dash = true;
        }
    }
    out.trim_matches('-').to_string()
}

fn template_choice_to_kind(choice: &TemplateChoice) -> TemplateKind {
    match choice {
        TemplateChoice::GenericProject => TemplateKind::GenericProject,
        TemplateChoice::PythonService => TemplateKind::PythonService,
        TemplateChoice::NodeWeb => TemplateKind::NodeWeb,
        TemplateChoice::DesktopTauri => TemplateKind::DesktopTauri,
        TemplateChoice::Godot3DGame => TemplateKind::Godot3DGame,
    }
}
